export const ADD_COMMENT = 'ADD_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
// export const DELETE_COMMENT = 'DELETE_COMMENT';

export const FETCH_REQUESTED = 'COMMENTS/FETCH_REQUESTED';
export const FETCH_COMPLETE = 'COMMENTS/FETCH_COMPLETE';
export const FETCH_ERROR = 'COMMENTS/FETCH_ERROR';
export const CANCEL_FETCH_REQUESTED = 'COMMENTS/CANCEL_FETCH_REQUESTED';

export const DELETE_REQUESTED = 'COMMENTS/DELETE_REQUESTED';
export const DELETE_COMPLETE = 'COMMENTS/DELETE_COMPLETE';
export const DELETE_ERROR = 'COMMENTS/DELETE_ERROR';
export const CANCEL_DELETE_REQUESTED = 'COMMENTS/CANCEL_DELETE_REQUESTED';
