export const INCREMENT = 'INCREMENT';
export const INCREMENTBY = 'INCREMENTBY';
export const DECREMENT = 'DECREMENT';
export const DECREMENTBY = 'DECREMENTBY';
export const INCREMENT_IF_ODD = 'INCREMENT_IF_ODD';
export const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
