export const ADD_TODO = 'ADD_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';
export const COMPLETE_ALL_TODOS = 'COMPLETE_ALL_TODOS';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export const SHOW_ALL = 'SHOW_ALL';
export const SHOW_ACTIVE = 'SHOW_ACTIVE';
export const SHOW_COMPLETED = 'SHOW_COMPLETED';
