export const ADD_USER = 'ADD_USER';
export const EDIT_USER = 'EDIT_USER';
// export const DELETE_USER = 'DELETE_USER';

export const FETCH_REQUESTED = 'USERS/FETCH_REQUESTED';
export const FETCH_COMPLETE = 'USERS/FETCH_COMPLETE';
export const FETCH_ERROR = 'USERS/FETCH_ERROR';
export const CANCEL_FETCH_REQUESTED = 'USERS/CANCEL_FETCH_REQUESTED';

export const DELETE_REQUESTED = 'USERS/DELETE_REQUESTED';
export const DELETE_COMPLETE = 'USERS/DELETE_COMPLETE';
export const DELETE_ERROR = 'USERS/DELETE_ERROR';
export const CANCEL_DELETE_REQUESTED = 'USERS/CANCEL_DELETE_REQUESTED';

// get user
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE';
