name: CI
on: [push, pull_request]

jobs:
    lint:
        strategy:
            fail-fast: false
            matrix:
                node-version: ['14.x', '16.x', '18.x']
        name: Lint code (${{ matrix.node-version }})
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'version'
            - run: npm install
            - run: npm run lint
    test:
        strategy:
            fail-fast: false
            matrix:
                node-version: ['14.x', '16.x', '18.x']
        name: Test code (${{ matrix.node-version }})
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'version'
            - run: npm install
            - run: npm run test
